# Generated by Django 4.0.4 on 2022-05-20 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='vote_to_delete',
            new_name='mark_to_delete',
        ),
    ]
